---
- hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - vars/defaults.yml
  - vars/vars.yml
  module_defaults:
    group/aws:
      region: '{{ aws_region }}'
  tasks:
  - cloudformation_facts:
      stack_name: static-ecs-cluster
  - ecs_service:
      state: present
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: ssh-targets-{{ item + 1 }}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ssh-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - ecs_service:
      state: present
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: cisco-ios-targets-{{ item + 1}}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ios-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - name: Scale instances down to zero
    cloudformation:
      template: ./cfn/ecs-static-size-cluster.yaml
      stack_name: static-ecs-cluster
      template_parameters:
        ParentVPCStack: scale-test-vpc
        SubnetsReach: Public
        InstanceType: c5.4xlarge
        SpotBidPrice: 0.20
        MaxSize: 8
        DesiredCapacity: 0
        MinSize: 0
        KeyName: '{{ key_name | default("") }}'
  - ecs_service:
      state: absent
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: ssh-targets-{{ item + 1 }}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ssh-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - ecs_service:
      state: absent
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: cisco-ios-targets-{{ item + 1}}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ios-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - ecs_taskdefinition_facts:
      task_definition: ssh-ansible-targets
    register: td
  - ecs_taskdefinition:
      arn: '{{ td.task_definition_arn }}'
      family: ssh-ansible-targets
      state: absent
  - ecs_taskdefinition_facts:
      task_definition: ios-ansible-targets
    register: td
  - ecs_taskdefinition:
      arn: '{{ td.task_definition_arn }}'
      family: ios-ansible-targets
      state: absent
  - cloudformation:
      template: ./cfn/ecs-static-size-cluster.yaml
      state: absent
      stack_name: static-ecs-cluster
  - cloudformation:
      template: ./cfn/vpc-2azs.yaml
      state: absent
      stack_name: scale-test-vpc
      template_parameters:
        ClassB: 99
